# Welcome to Jekyll!
#

# Site settings
title: Funky Flavour - Sweet Magic, Server with a Smile
description: |
  Sweet Magic, 
  Served with a Smile
owner: Funky Flavour
first_published: 2024 
email: info@funkyflavour.nl
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.funkyflavour.nl" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:info@funkyflavour.nl
  #flickr:
  instagram: https://instagram.com/funkyflavour_official
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
